In [1]:
import numpy as np
import pandas as pd

# 导入数据1

In [2]:
data1 = np.load('data1.npy', encoding='bytes')

In [3]:
data1['vh_size']

array([ 0,  0,  0, ..., 20, 22, 20], dtype=int32)

# 删除空缺数据

In [4]:
data1_not_empty = data1[data1['vt_size']>0]

In [5]:
data1_not_empty.shape

(2743,)

In [6]:
df_not_empty = pd.DataFrame(data1_not_empty)

In [7]:
df_not_empty['vt_size'].value_counts()

2    1700
3     459
4     432
1     152
Name: vt_size, dtype: int64

# 导入数据2

In [8]:
data2 = np.load('data2.npy', encoding='bytes')

In [9]:
data2['vh_size']

array([ 0,  0,  0, ..., 32,  2, 22], dtype=int32)

# 删除空缺数据

In [10]:
data2_not_empty = data2[data2['vt_size']>0]

In [11]:
data2_not_empty.shape

(78055,)

In [12]:
df_not_empty = pd.DataFrame(data2_not_empty)

In [13]:
df_not_empty['vt_size'].value_counts()

2    49073
4    12320
3    12316
1     4329
5       14
6        3
Name: vt_size, dtype: int64

# 导入数据3

In [14]:
data3 = np.load('data3.npy', encoding='bytes')

In [15]:
data3['vh_size']

array([10, 15,  0, ..., 10,  6,  2], dtype=int32)

# 删除空缺数据

In [16]:
data3_not_empty = data3[data3['vt_size']>0]

In [17]:
data3_not_empty.shape

(82939,)

In [18]:
df_not_empty = pd.DataFrame(data3_not_empty)

In [19]:
df_not_empty['vt_size'].value_counts()

2    52009
4    13115
3    13050
1     4755
5        9
6        1
Name: vt_size, dtype: int64

# 保存非空数据

In [20]:
np.save('data1_full.npy', data1_not_empty)

In [21]:
np.save('data2_full.npy', data2_not_empty)

In [22]:
np.save('data3_full.npy', data3_not_empty)

# 合并所有数据

In [39]:
data_all = np.concatenate((data1_not_empty, data2_not_empty, data3_not_empty), axis=0)

In [40]:
len(data_all['vh_size'])

163737

In [41]:
data_all['vh_size']

array([15, 23, 32, ..., 15,  7, 24], dtype=int32)

In [42]:
df_all = pd.DataFrame(data_all)

# 合并数据

In [2]:
data1_full = np.load('data1_full.npy')

In [3]:
data2_full = np.load('data2_full.npy')

In [4]:
data3_full = np.load('data3_full.npy')

In [5]:
data_all = np.concatenate((data1_full, data2_full, data3_full), axis=0)

In [6]:
len(data_all['vh_size'])

163737

In [6]:
np.save('data_all.npy', data_all)

MemoryError: 