# All Data

In [1]:
import numpy as np
import pandas as pd

In [42]:
data = np.load("data_all.npy")

In [132]:
len(data['vh_size'])

163737

# Part Data

In [54]:
data_part = np.load('data1_full.npy')

In [57]:
df_part = pd.DataFrame(data_part)

In [84]:
df_part.head(2)

vh_endcap  \
0  [1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -...   
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -...   

                                          vh_station  \
0      [1, 1, 1, 1, 3, 3, 4, 4, 1, 1, 1, 1, 3, 3, 4]   
1  [1, 1, 1, 1, 2, 1, 2, 3, 3, 4, 4, 4, 1, 1, 1, ...   

                                             vh_ring  \
0      [1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2]   
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   

                                           vh_sector  \
0      [3, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6, 6]   
1  [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, ...   

                                        vh_subsector  \
0      [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0]   
1  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...   

                                          vh_chamber  \
0  [15, 15, 15, 15, 15, 15, 15, 15, 34, 34, 34, 3...   
1  [23, 23, 23, 23, 12, 12, 12, 12, 12, 12, 12, 1...   

                                            vh_cscid  \
0      [1, 1, 1, 4, 4, 4, 4, 4, 2, 2, 5, 5, 5, 5, 5]   
1  [3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, ...   

                                               vh_bx  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                             vh_type  \
0      [3, 3, 3, 1, 1, 2, 1, 2, 1, 3, 1, 2, 1, 2, 1]   
1  [1, 1, 3, 3, 3, 4, 1, 1, 2, 1, 2, 2, 1, 3, 3, ...   

                                         vh_neighbor  ... vp_event   vp_pdgid  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  ...   [0, 0]  [-13, 13]   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  ...   [0, 0]  [-13, 13]   

  vp_status vp_genp vp_size  ve_event ve_run ve_lumi ve_npv ve_size  
0    [1, 1]  [0, 1]       2  [244986]    [1]   [246]    [0]       1  
1    [1, 1]  [0, 1]       2  [244987]    [1]   [246]    [0]       1  

[2 rows x 82 columns]

# Column Names

In [60]:
column_names = df_part.columns

In [61]:
column_names

Index(['vh_endcap', 'vh_station', 'vh_ring', 'vh_sector', 'vh_subsector',
       'vh_chamber', 'vh_cscid', 'vh_bx', 'vh_type', 'vh_neighbor', 'vh_strip',
       'vh_wire', 'vh_roll', 'vh_pattern', 'vh_quality', 'vh_bend', 'vh_time',
       'vh_fr', 'vh_emtf_phi', 'vh_emtf_theta', 'vh_sim_phi', 'vh_sim_theta',
       'vh_sim_eta', 'vh_sim_r', 'vh_sim_z', 'vh_sim_tp1', 'vh_sim_tp2',
       'vh_size', 'vt_pt', 'vt_xml_pt', 'vt_phi', 'vt_eta', 'vt_theta', 'vt_q',
       'vt_address', 'vt_mode', 'vt_endcap', 'vt_sector', 'vt_bx',
       'vt_hitref1', 'vt_hitref2', 'vt_hitref3', 'vt_hitref4', 'vt_size',
       'vu_pt', 'vu_phi', 'vu_eta', 'vu_theta', 'vu_q', 'vu_vx', 'vu_vy',
       'vu_vz', 'vu_rinv', 'vu_chi2', 'vu_ndof', 'vu_sector', 'vu_sim_pt',
       'vu_sim_phi', 'vu_sim_eta', 'vu_sim_tp', 'vu_sim_pdgid', 'vu_sim_assoc',
       'vu_size', 'vp_pt', 'vp_phi', 'vp_eta', 'vp_theta', 'vp_vx', 'vp_vy',
       'vp_vz', 'vp_q', 'vp_bx', 'vp_event', 'vp_pdgid', 'vp_status',
       'vp_genp', '

# Create Hit Data Container

In [64]:
hit_names = column_names[0:27]
hit_names

Index(['vh_endcap', 'vh_station', 'vh_ring', 'vh_sector', 'vh_subsector',
       'vh_chamber', 'vh_cscid', 'vh_bx', 'vh_type', 'vh_neighbor', 'vh_strip',
       'vh_wire', 'vh_roll', 'vh_pattern', 'vh_quality', 'vh_bend', 'vh_time',
       'vh_fr', 'vh_emtf_phi', 'vh_emtf_theta', 'vh_sim_phi', 'vh_sim_theta',
       'vh_sim_eta', 'vh_sim_r', 'vh_sim_z', 'vh_sim_tp1', 'vh_sim_tp2'],
      dtype='object')

In [67]:
hit_count = data['vh_size'].sum()
hit_count

3240189

In [68]:
hit_df = pd.DataFrame(index = range(hit_count), columns = hit_names)

# Transpose and Fill

In [80]:
for name in hit_names:
    hit_df[name] = np.hstack(data[name])

# Save Hit Data

In [82]:
hit_df.to_csv('hit_df.csv')

# Add Event Index

In [86]:
event_count = len(data)
event_count

163737

In [88]:
hit_size = data['vh_size']

In [127]:
event_index = np.empty(0,dtype=np.int32)

In [128]:
for i in range(len(hit_size)):
    event_index = np.hstack((event_index, np.full(hit_size[i],i,np.int32)))

In [129]:
print(len(event_index))

3240189


In [130]:
event_index

array([     0,      0,      0, ..., 163736, 163736, 163736], dtype=int32)

In [131]:
hit_df['ve_id'] = event_index

In [132]:
hit_df

vh_endcap  vh_station  vh_ring  vh_sector  vh_subsector  vh_chamber  \
0                1           1        1          3             1          15   
1                1           1        1          3             1          15   
2                1           1        1          3             1          15   
3                1           1        2          3             1          15   
4                1           3        2          3             0          15   
5                1           3        2          3             0          15   
6                1           4        2          3             0          15   
7                1           4        2          3             0          15   
8               -1           1        1          6             1          34   
9               -1           1        1          6             1          34   
10              -1           1        2          6             1          34   
11              -1           1        2          6             1          34   
12              -1           3        2          6             0          34   
13              -1           3        2          6             0          34   
14              -1           4        2          6             0          34   
15               1           1        1          4             1          23   
16               1           1        1          4             1          23   
17               1           1        1          4             1          23   
18               1           1        1          4             1          23   
19               1           2        1          4             0          12   
20               1           1        1          4             0          12   
21               1           2        1          4             0          12   
22               1           3        1          4             0          12   
23               1           3        1          4             0          12   
24               1           4        1          4             0          12   
25               1           4        1          4             0          12   
26               1           4        1          4             0          12   
27              -1           1        1          1             1           5   
28              -1           1        1          1             1           5   
29              -1           1        1          1             1           5   
...            ...         ...      ...        ...           ...         ...   
3240159          1           3        2          2             0          11   
3240160          1           3        3          2             0          11   
3240161          1           4        2          2             0          11   
3240162         -1           2        2          5             0          29   
3240163         -1           3        2          5             0          29   
3240164         -1           4        2          5             0          29   
3240165          1           1        2          2             1           9   
3240166          1           1        2          2             1           9   
3240167          1           2        2          2             0           9   
3240168          1           2        2          2             0           9   
3240169          1           3        2          2             0           9   
3240170          1           3        2          2             0           9   
3240171          1           4        2          2             0           9   
3240172          1           4        3          2             0           9   
3240173         -1           1        2          3             2          20   
3240174         -1           1        2          3             2          20   
3240175         -1           2        2          3             0          20   
3240176         -1           2        2          3             0          20   
3240177  

In [133]:
hit_df.to_csv('hit_df.csv')

# Feature Preselection

# Median

In [2]:
hit_df = pd.read_csv('hit_df.csv', index_col = 0)

/home/lipeize/anaconda3/envs/tf_test/lib/python3.6/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [3]:
hit_df.head(3)

vh_endcap  vh_station  vh_ring  vh_sector  vh_subsector  vh_chamber  \
0          1           1        1          3             1          15   
1          1           1        1          3             1          15   
2          1           1        1          3             1          15   

   vh_cscid  vh_bx  vh_type  vh_neighbor  ...  vh_emtf_phi  vh_emtf_theta  \
0         1      0        3            0  ...         1755             47   
1         1      0        3            0  ...         1752             47   
2         1      0        3            0  ...         1688             47   

   vh_sim_phi  vh_sim_theta  vh_sim_eta   vh_sim_r   vh_sim_z  vh_sim_tp1  \
0   142.25080     21.884860    1.643317  228.14865  567.97125          -1   
1   142.19790     21.884146    1.643350  228.14046  567.97125          -1   
2   141.13908     21.873484    1.643849  228.01768  567.97125          -1   

   vh_sim_tp2  ve_id  
0          -1      0  
1          -1      0  
2          -1      0  

[3 rows x 28 columns]

## Split Endcaps

In [4]:
hit_ec1 = hit_df[hit_df['vh_endcap']==1]

In [5]:
hit_ec2 = hit_df[hit_df['vh_endcap']==-1]

## Get Median

In [43]:
hit_ec1.head()

vh_endcap  vh_station  vh_ring  vh_sector  vh_subsector  vh_chamber  \
0          1           1        1          3             1          15   
1          1           1        1          3             1          15   
2          1           1        1          3             1          15   
3          1           1        2          3             1          15   
4          1           3        2          3             0          15   

   vh_cscid  vh_bx  vh_type  vh_neighbor  ...  vh_emtf_phi  vh_emtf_theta  \
0         1      0        3            0  ...         1755             47   
1         1      0        3            0  ...         1752             47   
2         1      0        3            0  ...         1688             47   
3         4      0        1            0  ...         1680             49   
4         4      0        1            0  ...         1687             50   

   vh_sim_phi  vh_sim_theta  vh_sim_eta   vh_sim_r   vh_sim_z  vh_sim_tp1  \
0   142.25080     21.884860    1.643317  228.14865  567.97125          -1   
1   142.19790     21.884146    1.643350  228.14046  567.97125          -1   
2   141.13908     21.873484    1.643849  228.01768  567.97125          -1   
3   140.98416     22.409435    1.619029  293.33813  711.35913           0   
4   141.13275     22.423573    1.618382  381.45663  924.40350           0   

   vh_sim_tp2  ve_id  
0          -1      0  
1          -1      0  
2          -1      0  
3           0      0  
4           0      0  

[5 rows x 28 columns]

In [51]:
hit_ec1.shape

(1614816, 28)

In [56]:
ids = hit_ec1['ve_id'].unique()

In [58]:
theta_median = []

In [59]:
for i in ids:
    theta_median.append(hit_ec1[hit_ec1['ve_id']==i]['vh_sim_theta'].median())

In [65]:
phi_median = []

In [66]:
for i in ids:
    phi_median.append(hit_ec1[hit_ec1['ve_id']==i]['vh_sim_phi'].median())

In [75]:
phi_median = []

In [76]:
for i in ids:
    phi_median.append(hit_ec1[hit_ec1['ve_id']==i]['vh_sim_eta'].median())

In [62]:
median_df = pd.DataFrame()

In [63]:
median_df['ve_id'] = ids

In [64]:
median_df['theta_median'] = theta_median

In [67]:
median_df['phi_median'] = phi_median

In [ ]:
median_df['eta_median'] = eta_median

In [68]:
median_df

ve_id  theta_median  phi_median
0            0     22.381725  141.058455
1            1     15.110317 -141.673995
2            2     21.016869 -110.063550
3            3     10.484757  113.099700
4            4     13.612604   47.813921
5            5     14.388596  -82.739825
6            6     21.175463  138.888345
7            7     32.415860  159.130200
8            9     18.969759   95.155700
9           10     24.973456   -6.401951
10          11     34.508940   63.602818
11          12     15.068190  -65.088550
12          13     13.910933   78.338613
13          14     28.113377  -36.143538
14          15     29.765286 -176.914270
15          16     17.658613  -12.466813
16          17     10.592312  -88.199675
17          18     14.755083 -115.929430
18          19     23.039959  -77.338960
19          20     36.538559   -9.833919
20          21     12.499372    5.268401
21          22     33.298300  155.296350
22          23     23.270005  120.198007
23          24     17.394592  -79.398515
24          25     27.205833   80.138080
25          26     22.866474  -80.461754
26          27     21.682045   45.929790
27          28     18.335256 -134.464325
28          29     13.373705   77.662830
29          30     12.012946    6.013578
...        ...           ...         ...
163460  163707     14.624681  -47.799778
163461  163708     26.850828  141.795260
163462  163709     13.371843  -61.798775
163463  163710     19.239065  -78.348445
163464  163711     15.544653  -33.666298
163465  163712     13.418500 -117.819590
163466  163713     13.335582   21.057848
163467  163714     15.768400  110.531810
163468  163715     31.620956  176.260345
163469  163716     36.737916  -96.890377
163470  163717     36.155163    0.164904
163471  163718     16.997568  176.192950
163472  163719     10.638957   14.846953
163473  163720     32.526846  114.299490
163474  163721     10.601449   -7.832253
163475  163722     16.033472  -19.667225
163476  163723     32.924471  -26.165355
163477  163724     13.296372  102.609820
163478  163725     23.132822   20.834514
163479  163726     27.145916  124.794820
163480  163727     27.077446 -158.432605
163481  163728     28.474266 -133.288725
163482  163729     17.050055  -15.934568
163483  163730     36.968010  117.147360
163484  163731     30.701077 -149.867175
163485  163732     19.438308  -33.027797
163486  163733     12.672078   91.677205
163487  163734     10.239648  145.129790
163488  163735     33.554930   97.198918
163489  163736     25.561912   83.790215

[163490 rows x 3 columns]

In [69]:
hit_ec1_new = hit_ec1.join(median_df.set_index('ve_id'), on='ve_id')

In [70]:
hit_ec1_new

vh_endcap  vh_station  vh_ring  vh_sector  vh_subsector  vh_chamber  \
0                1           1        1          3             1          15   
1                1           1        1          3             1          15   
2                1           1        1          3             1          15   
3                1           1        2          3             1          15   
4                1           3        2          3             0          15   
5                1           3        2          3             0          15   
6                1           4        2          3             0          15   
7                1           4        2          3             0          15   
15               1           1        1          4             1          23   
16               1           1        1          4             1          23   
17               1           1        1          4             1          23   
18               1           1        1          4             1          23   
19               1           2        1          4             0          12   
20               1           1        1          4             0          12   
21               1           2        1          4             0          12   
22               1           3        1          4             0          12   
23               1           3        1          4             0          12   
24               1           4        1          4             0          12   
25               1           4        1          4             0          12   
26               1           4        1          4             0          12   
38               1           1        1          4             2          26   
39               1           2        1          4             0          13   
40               1           2        1          4             0          13   
41               1           2        1          4             0          13   
42               1           1        1          4             2          26   
43               1           2        1          4             0          13   
44               1           3        2          4             0          26   
45               1           4        2          4             0          26   
46               1           4        2          4             0          26   
47               1           1        1          5             2          26   
...            ...         ...      ...        ...           ...         ...   
3240116          1           4        2          6             0          34   
3240117          1           4        2          6             0          34   
3240127          1           1        4          2             1          10   
3240128          1           2        1          2             0           5   
3240129          1           1        1          2             0           6   
3240130          1           2        1          2             0           5   
3240131          1           3        1          2             0           5   
3240132          1           3        1          2             0           5   
3240133          1           4        1          2             0           5   
3240134          1           4        1          2             0           5   
3240143          1           1        4          3             1          15   
3240144          1           2        1          3             0           8   
3240145          1           1        1          3             0           8   
3240146          1           2        1          3             0           8   
3240147          1           3        1          3             0           8   
3240148          1           3        1          3             0           8   
3240149          1           4        1          3             0           8   
3240150          1           4        1          3             0           8   
3240158  

In [73]:
hit_ec1_new['delta_theta'] = hit_ec1_new['vh_sim_theta'] - hit_ec1_new['theta_median']

In [74]:
hit_ec1_new['delta_phi'] = hit_ec1_new['vh_sim_phi'] - hit_ec1_new['phi_median']

In [77]:
hit_ec1_new

vh_endcap  vh_station  vh_ring  vh_sector  vh_subsector  vh_chamber  \
0                1           1        1          3             1          15   
1                1           1        1          3             1          15   
2                1           1        1          3             1          15   
3                1           1        2          3             1          15   
4                1           3        2          3             0          15   
5                1           3        2          3             0          15   
6                1           4        2          3             0          15   
7                1           4        2          3             0          15   
15               1           1        1          4             1          23   
16               1           1        1          4             1          23   
17               1           1        1          4             1          23   
18               1           1        1          4             1          23   
19               1           2        1          4             0          12   
20               1           1        1          4             0          12   
21               1           2        1          4             0          12   
22               1           3        1          4             0          12   
23               1           3        1          4             0          12   
24               1           4        1          4             0          12   
25               1           4        1          4             0          12   
26               1           4        1          4             0          12   
38               1           1        1          4             2          26   
39               1           2        1          4             0          13   
40               1           2        1          4             0          13   
41               1           2        1          4             0          13   
42               1           1        1          4             2          26   
43               1           2        1          4             0          13   
44               1           3        2          4             0          26   
45               1           4        2          4             0          26   
46               1           4        2          4             0          26   
47               1           1        1          5             2          26   
...            ...         ...      ...        ...           ...         ...   
3240116          1           4        2          6             0          34   
3240117          1           4        2          6             0          34   
3240127          1           1        4          2             1          10   
3240128          1           2        1          2             0           5   
3240129          1           1        1          2             0           6   
3240130          1           2        1          2             0           5   
3240131          1           3        1          2             0           5   
3240132          1           3        1          2             0           5   
3240133          1           4        1          2             0           5   
3240134          1           4        1          2             0           5   
3240143          1           1        4          3             1          15   
3240144          1           2        1          3             0           8   
3240145          1           1        1          3             0           8   
3240146          1           2        1          3             0           8   
3240147          1           3        1          3             0           8   
3240148          1           3        1          3             0           8   
3240149          1           4        1          3             0           8   
3240150          1           4        1          3             0           8   
3240158  

## Save Hit Data of Endcap 1 with Median

In [78]:
hit_ec1_new.to_csv('hit_ec1_median_delta.csv')

## Load Hit Data of Endcap 1 with Median

In [2]:
hit_ec1 = pd.read_csv('hit_ec1_median_delta.csv', index_col = 0)

/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:522: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


# Sort

In [4]:
hit_ec1 = hit_ec1.sort_values(by=['ve_id', 'delta_theta', 'delta_phi'])

In [13]:
hit_ec1.head(80)

vh_endcap  vh_station  vh_ring  vh_sector  vh_subsector  vh_chamber  \
2            1           1        1          3             1          15   
1            1           1        1          3             1          15   
0            1           1        1          3             1          15   
6            1           4        2          3             0          15   
3            1           1        2          3             1          15   
4            1           3        2          3             0          15   
5            1           3        2          3             0          15   
7            1           4        2          3             0          15   
20           1           1        1          4             0          12   
26           1           4        1          4             0          12   
25           1           4        1          4             0          12   
15           1           1        1          4             1          23   
16           1           1        1          4             1          23   
24           1           4        1          4             0          12   
22           1           3        1          4             0          12   
21           1           2        1          4             0          12   
19           1           2        1          4             0          12   
17           1           1        1          4             1          23   
18           1           1        1          4             1          23   
23           1           3        1          4             0          12   
44           1           3        2          4             0          26   
53           1           3        2          5             0          26   
45           1           4        2          4             0          26   
54           1           4        2          5             0          26   
42           1           1        1          4             2          26   
51           1           1        1          5             2          26   
43           1           2        1          4             0          13   
52           1           2        1          5             0          13   
46           1           4        2          4             0          26   
55           1           4        2          5             0          26   
..         ...         ...      ...        ...           ...         ...   
90           1           1        1          1             2           6   
96           1           3        1          1             0           3   
95           1           2        1          1             0           3   
98           1           4        1          1             0           3   
92           1           2        1          1             0           3   
91           1           2        1          1             0           3   
97           1           3        1          1             0           3   
135          1           2        1          5             0          15   
136          1           2        1          5             0          15   
139          1           3        1          5             0          15   
138          1           3        1          5             0          15   
140          1           4        1          5             0          15   
134          1           1        1          5             1          29   
137          1           1        1          5             0          15   
141          1           4        1          5             0          15   
132          1           1        1          5             1          29   
133          1           1        1          5             1          29   
161          1           4        2          3             0          15   
156          1           1        1          3             1          15   
160          1           4        2          3             0          15   
159          1           2        1          3       

# Split Virtual Stations

## ME0

type = 4

In [86]:
hit_me0 = hit_ec1[hit_ec1['vh_type']==4]

In [87]:
hit_me0_sel = hit_me0[['ve_id', 'delta_theta', 'delta_phi', 'vh_bend', 'vh_fr']]

Choose the first hit

In [89]:
me0_ec1 = hit_me0_sel.drop_duplicates(subset = 've_id', keep = 'first')

In [90]:
me0_ec1.to_csv('me0_ec1.csv')

## ME1

type = 1

station = 1

ME

In [91]:
hit_me = hit_ec1[hit_ec1['vh_type']==1]

ME1

In [92]:
hit_me1 = hit_me[hit_me['vh_station']==1]

In [93]:
hit_me1_sel = hit_me1[['ve_id', 'delta_theta', 'delta_phi', 'vh_bend', 'vh_fr']]

In [94]:
me1_ec1 = hit_me1_sel.drop_duplicates(subset = 've_id', keep = 'first')

In [95]:
me1_ec1.to_csv('me1_ec1.csv')

## ME1/1

type = 1

station = 1

ring = 1 or 4

In [96]:
hit_me11b = hit_me1[hit_me1['vh_ring']==1]

In [97]:
hit_me11a = hit_me1[hit_me1['vh_ring']==4]

In [98]:
hit_me11 = pd.concat([hit_me11b, hit_me11a])

In [99]:
hit_me11 = hit_me11.sort_values(by=['ve_id'])

In [101]:
hit_me11_sel = hit_me11[['ve_id', 'delta_theta', 'delta_phi', 'vh_bend', 'vh_fr']]

In [102]:
me11_ec1 = hit_me11_sel.drop_duplicates(subset = 've_id', keep = 'first')

In [104]:
me11_ec1.to_csv('me11_ec1')

## ME1/2

type = 1

station = 1

ring = 2 or 3

In [105]:
hit_me12a = hit_me1[hit_me1['vh_ring']==2]
hit_me12b = hit_me1[hit_me1['vh_ring']==3]

In [106]:
hit_me12 = pd.concat([hit_me12b, hit_me12a])

In [107]:
hit_me12 = hit_me12.sort_values(by=['ve_id'])

In [108]:
hit_me12['vh_pattern'].value_counts()

10    52160
8      7875
9      7762
4       854
5       659
6       473
7       398
2       339
3       304
Name: vh_pattern, dtype: int64

In [121]:
hit_me12_sel = hit_me12[['ve_id', 'delta_theta', 'delta_phi', 'vh_bend', 'vh_fr']]

In [122]:
me12_ec1 = hit_me12_sel.drop_duplicates(subset = 've_id', keep = 'first')

In [123]:
me12_ec1.to_csv('me12_ec1')

## ME2

type = 1

station = 2

In [112]:
hit_me2 = hit_me[hit_me['vh_station']==2]

In [124]:
hit_me2_sel = hit_me2[['ve_id', 'delta_theta', 'delta_phi', 'vh_bend', 'vh_fr']]

In [125]:
me2_ec1 = hit_me2_sel.drop_duplicates(subset = 've_id', keep = 'first')

In [126]:
me2_ec1.to_csv('me2_ec1.csv')

## ME3

type = 1

station = 3

In [117]:
hit_me3 = hit_me[hit_me['vh_station']==3]

In [127]:
hit_me3_sel = hit_me3[['ve_id', 'delta_theta', 'delta_phi', 'vh_bend', 'vh_fr']]

In [136]:
me3_ec1 = hit_me3_sel.drop_duplicates(subset = 've_id', keep = 'first')

In [129]:
me3_ec1.to_csv('me3_ec1')

## ME4

type = 1

station = 4

In [130]:
hit_me4 = hit_me[hit_me['vh_station']==4]

In [131]:
hit_me4_sel = hit_me4[['ve_id', 'delta_theta', 'delta_phi', 'vh_bend', 'vh_fr']]

In [134]:
me4_ec1 = hit_me4_sel.drop_duplicates(subset = 've_id', keep = 'first')

In [135]:
me4_ec1.to_csv('me4_ec1.csv')

## GE1

type = 3

station = 1

GE

In [80]:
hit_ge = hit_ec1[hit_ec1['vh_type']==3]

GE1

In [81]:
hit_ge1 = hit_ge[hit_ge['vh_station']==1]

In [82]:
hit_ge1_sel = hit_ge1[['ve_id', 'vh_sim_phi', 'vh_sim_theta']]

In [83]:
h7 = hit_ge1_sel.drop_duplicates(subset = 've_id', keep = 'first')

In [84]:
h7

ve_id  vh_sim_phi  vh_sim_theta
2             0  141.139080     21.873484
17            1 -141.403870     15.427406
38            2 -110.185455     21.433216
90            4   47.960857     13.519802
134           5  -83.096730     14.394488
157           6  139.178760     21.871603
187           9   95.426340     19.082850
227          12  -64.952820     14.648970
263          13   78.543170     14.378797
320          16  -12.885361     18.413237
357          18 -118.755000     14.377594
453          24  -79.973500     17.745024
508          27   45.742386     21.487028
542          29   77.378970     13.412887
638          34   62.568160     21.889477
681          37 -118.755000     16.546057
716          38   80.344410     19.026780
732          39   62.832508     16.561487
771          40  168.860920     21.436966
802          42 -140.821240     19.028275
865          45 -173.360820     18.421013
981          51   -8.119629     15.776064
1008         52   65.689690     18.440107
1041         54   72.621040     17.044370
1109         59  172.621030     15.783681
1131         60   19.602602     16.542738
1152         61  160.768260     20.405317
1255         66   33.202385     17.052662
1300         69   49.761562     15.768118
1541         81  165.847780     15.807414
...         ...         ...           ...
3238661  163657  171.403880     21.438965
3238773  163663 -144.468340     15.467768
3238789  163664 -153.783080     23.166382
3238805  163665  136.639160     14.398076
3238850  163667 -176.164170     15.455970
3238892  163670   83.519220     19.059814
3238904  163671  -52.938213     21.458763
3238931  163672 -135.637010     20.458029
3238960  163674  -62.832508     13.415158
3239098  163681 -164.889420     16.599463
3239158  163683  111.774506     17.035270
3239362  163693   51.721565     14.600909
3239382  163694  -59.284710     17.746319
3239437  163696 -104.942010     16.600700
3239489  163700  -11.297963     18.395868
3239500  163701 -146.850430     15.790653
3239520  163702 -154.468340     18.443748
3239576  163705 -165.900500     17.068714
3239636  163707  -47.855020     14.604394
3239691  163709  -61.615685     13.404497
3239725  163710  -79.496635     19.027142
3239739  163711  -32.356600     15.780670
3239753  163712 -118.225494     13.405556
3239791  163713   21.139074     13.401914
3239809  163714  110.397390     15.768349
3239856  163718  175.373700     16.593466
3239956  163722  -19.867530     16.542404
3239984  163724  102.621030     13.412887
3240073  163729  -16.111422     16.578442
3240111  163732  -30.344410     18.391775

[64063 rows x 3 columns]

## GE2

type = 3

station = 2

GE2

In [42]:
hit_ge2 = hit_ge[hit_ge['vh_station']==2]

In [43]:
hit_ge2_sel = hit_ge2[['ve_id', 'vh_sim_phi', 'vh_sim_theta']]

In [44]:
h8 = hit_ge2_sel.drop_duplicates(subset = 've_id', keep = 'first')

## RE1

type = 2

station = 1

RE

In [45]:
hit_re = hit_ec1[hit_ec1['vh_type']==2]

RE1

In [46]:
hit_re1 = hit_re[hit_re['vh_station']==1]

In [47]:
hit_re1_sel = hit_re1[['ve_id', 'vh_sim_phi', 'vh_sim_theta']]

In [48]:
h9 = hit_re1_sel.drop_duplicates(subset = 've_id', keep = 'first')

## RE2

type = 2

station = 2

RE2

In [49]:
hit_re2 = hit_re[hit_re['vh_station']==2]

In [50]:
hit_re2_sel = hit_re2[['ve_id', 'vh_sim_phi', 'vh_sim_theta']]

In [51]:
h10 = hit_re2_sel.drop_duplicates(subset = 've_id', keep = 'first')

## RE3

type = 2

station = 3

RE3

In [52]:
hit_re3 = hit_re[hit_re['vh_station']==3]

In [54]:
hit_re3_sel = hit_re3[['ve_id', 'vh_sim_phi', 'vh_sim_theta']]

In [55]:
h11 = hit_re3_sel.drop_duplicates(subset = 've_id', keep = 'first')

## RE4

type = 2

station = 4

RE4

In [56]:
hit_re4 = hit_re[hit_re['vh_station']==4]

In [57]:
hit_re4_sel = hit_re4[['ve_id', 'vh_sim_phi', 'vh_sim_theta']]

In [58]:
h12 = hit_re4_sel.drop_duplicates(subset = 've_id', keep = 'first')

## GE1 + ME0

## GE2 + RE2

## RE3/2 RE3/3

## RE4/2 RE4/3

# Track Variables

## Medians

In [137]:
medians = hit_ec1[['ve_id', 'phi_median', 'theta_median']]

In [138]:
medians = medians.drop_duplicates(subset = 've_id', keep = 'first')

## Pattern Recognition

# Merge Track

In [59]:
h1['exist'] = 1

/home/lipeize/anaconda3/envs/tf_test/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [60]:
h1['exist'] = 1
h2['exist'] = 1
h3['exist'] = 1
h4['exist'] = 1
h5['exist'] = 1
h6['exist'] = 1
h7['exist'] = 1
h8['exist'] = 1
h9['exist'] = 1
h10['exist'] = 1
h11['exist'] = 1
h12['exist'] = 1

/home/lipeize/anaconda3/envs/tf_test/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/lipeize/anaconda3/envs/tf_test/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/lipeize/anaconda3/envs/tf_test/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = v

## Join 4 station data

ME1 ME2 ME3 ME4

In [150]:
index = pd.DataFrame(np.arange(1, 163737, dtype=np.int32), columns = ['ve_id'])

In [151]:
me1_ec1['exist'] = 1
me2_ec1['exist'] = 1
me3_ec1['exist'] = 1
me4_ec1['exist'] = 1

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/p

In [152]:
tracks = index.join(me1_ec1.set_index('ve_id'), on='ve_id')

In [153]:
tracks = tracks.join(me2_ec1.set_index('ve_id'), on='ve_id', rsuffix='_me2')
tracks = tracks.join(me3_ec1.set_index('ve_id'), on='ve_id', rsuffix='_me3')
tracks = tracks.join(me4_ec1.set_index('ve_id'), on='ve_id', rsuffix='_me4')

In [155]:
tracks['hit_count'] = tracks['exist'].fillna(0) + tracks['exist_me2'].fillna(0) + tracks['exist_me3'].fillna(0) + tracks['exist_me4'].fillna(0)

In [156]:
tracks['hit_count'].value_counts()

4.0    94542
3.0    43324
2.0    21104
1.0     4327
0.0      439
Name: hit_count, dtype: int64

## Join 12 station data

In [63]:
tracks = tracks.join(h2.set_index('ve_id'), on='ve_id', rsuffix='_h2')
tracks = tracks.join(h3.set_index('ve_id'), on='ve_id', rsuffix='_h3')
tracks = tracks.join(h4.set_index('ve_id'), on='ve_id', rsuffix='_h4')
tracks = tracks.join(h5.set_index('ve_id'), on='ve_id', rsuffix='_h5')
tracks = tracks.join(h6.set_index('ve_id'), on='ve_id', rsuffix='_h6')
tracks = tracks.join(h7.set_index('ve_id'), on='ve_id', rsuffix='_h7')
tracks = tracks.join(h8.set_index('ve_id'), on='ve_id', rsuffix='_h8')
tracks = tracks.join(h9.set_index('ve_id'), on='ve_id', rsuffix='_h9')
tracks = tracks.join(h10.set_index('ve_id'), on='ve_id', rsuffix='_h10')
tracks = tracks.join(h11.set_index('ve_id'), on='ve_id', rsuffix='_h11')
tracks = tracks.join(h12.set_index('ve_id'), on='ve_id', rsuffix='_h12')

Create a column to indicate hit counts.

In [72]:
tracks['hit_count'] = tracks['exist'].fillna(0) + tracks['exist_h2'].fillna(0) + tracks['exist_h3'].fillna(0)  + tracks['exist_h4'].fillna(0) + tracks['exist_h5'].fillna(0) + tracks['exist_h6'].fillna(0) + tracks['exist_h7'].fillna(0) +tracks['exist_h8'].fillna(0) +tracks['exist_h9'].fillna(0) +tracks['exist_h10'].fillna(0) +tracks['exist_h11'].fillna(0) +tracks['exist_h12'].fillna(0)

In [77]:
tracks['hit_count'].value_counts()

8.0     54178
7.0     45933
6.0     20137
9.0     13967
2.0     10422
5.0      6585
3.0      5491
1.0      3273
4.0      3136
10.0      364
0.0       247
11.0        3
Name: hit_count, dtype: int64

## Fill NaN

## Add Track Variable

In [158]:
tracks = tracks.join(medians.set_index('ve_id'), on='ve_id')

## Calculate hit counts

# Frequent Modes Analysis

# Target Value (y)

In [43]:
data['vp_pt']

array([array([30.163197, 30.163197], dtype=float32),
       array([45.87434, 45.87434], dtype=float32),
       array([89.10662, 89.10662], dtype=float32), ...,
       array([60.514774, 60.514774], dtype=float32),
       array([93.74769, 93.74769], dtype=float32),
       array([2.8926315, 2.8926315], dtype=float32)], dtype=object)

In [44]:
data['vp_q']

array([array([ 1, -1], dtype=int16), array([ 1, -1], dtype=int16),
       array([ 1, -1], dtype=int16), ..., array([ 1, -1], dtype=int16),
       array([ 1, -1], dtype=int16), array([ 1, -1], dtype=int16)],
      dtype=object)

In [45]:
data['vp_eta']

array([array([ 1.6087198, -1.6087198], dtype=float32),
       array([ 2.014989 , -2.0149887], dtype=float32),
       array([-1.7026838,  1.7026838], dtype=float32), ...,
       array([-2.412733,  2.412733], dtype=float32),
       array([ 1.1898016, -1.1898016], dtype=float32),
       array([-1.437928,  1.437928], dtype=float32)], dtype=object)

In [46]:
pt_df = pd.DataFrame(index = range(327472), columns = ['pt'])

In [47]:
np.reshape(np.hstack(data['vp_pt']), (-1, 2))

array([[30.163197 , 30.163197 ],
       [45.87434  , 45.87434  ],
       [89.10662  , 89.10662  ],
       ...,
       [60.514774 , 60.514774 ],
       [93.74769  , 93.74769  ],
       [ 2.8926315,  2.8926315]], dtype=float32)

In [48]:
pt_df['pt'] = np.hstack(data['vp_pt'])

In [55]:
pt = pd.DataFrame(np.reshape(np.hstack(data['vp_pt']), (-1, 2)), columns = ['pt', 'del'])

In [56]:
q = pd.DataFrame(np.reshape(np.hstack(data['vp_q']), (-1, 2)), columns = ['q1', 'q2'])

In [58]:
eta = pd.DataFrame(np.reshape(np.hstack(data['vp_eta']), (-1, 2)), columns = ['eta1', 'eta2'])

In [ ]:
index = pd.DataFrame(np.arange(1, 163737, dtype=np.int32), columns = ['ve_id'])

In [60]:
pt['q'] = np.sign(eta['eta1'])

In [63]:
del pt['del']

In [68]:
pt['q/pt'] = pt['q'] / pt['pt']

In [69]:
pt.head()

pt    q      q/pt
0  30.163197  1.0  0.033153
1  45.874340  1.0  0.021799
2  89.106621 -1.0 -0.011223
3  58.869408  1.0  0.016987
4  57.881783  1.0  0.017277

In [70]:
pt.to_csv('target.csv')

In [159]:
pt.head()

pt    q      q/pt
0  30.163197  1.0  0.033153
1  45.874340  1.0  0.021799
2  89.106621 -1.0 -0.011223
3  58.869408  1.0  0.016987
4  57.881783  1.0  0.017277

In [160]:
pt['ve_id'] = np.arange(1, 163737, dtype=np.int32)

## Add target variable

In [163]:
tracks = tracks.join(pt.set_index('ve_id'), on='ve_id')

# Out put data for models

In [170]:
new_tracks = tracks[tracks['hit_count']==4]

In [171]:
new_tracks['hit_count'].value_counts()

4.0    94542
Name: hit_count, dtype: int64

In [172]:
new_tracks.to_csv('tracks_4_stations_mode_1.csv')

In [168]:
new_tracks.head()

ve_id  delta_theta  delta_phi  vh_bend  vh_fr  exist  delta_theta_me2  \
0      1    -0.139176   0.213865      0.0    0.0    1.0         0.033934   
1      2    -0.467373  -0.149070      0.0    1.0    1.0        -0.179194   
2      3    -0.362438   0.064790      0.0    1.0    1.0        -0.031839   
3      4    -0.255659   0.122492      0.0    1.0    1.0         0.029521   
4      5     0.889810   7.102425      7.0    0.0    1.0              NaN   

   delta_phi_me2  vh_bend_me2  vh_fr_me2  ...  delta_phi_me4  vh_bend_me4  \
0       0.007785         -3.0        1.0  ...      -0.124695         -7.0   
1       0.000000          6.0        0.0  ...       0.067784          0.0   
2      -0.096170          4.0        1.0  ...       0.039160         -4.0   
3      -0.009989          0.0        0.0  ...      -0.141528        -10.0   
4            NaN          NaN        NaN  ...       0.008715          0.0   

   vh_fr_me4  exist_me4  hit_count  phi_median  theta_median         pt    q  \
0        0.0        1.0        4.0 -141.673995     15.110317  30.163197  1.0   
1        0.0        1.0        3.0 -110.063550     21.016869  45.874340  1.0   
2        0.0        1.0        4.0  113.099700     10.484757  89.106621 -1.0   
3        1.0        1.0        4.0   47.813921     13.612605  58.869408  1.0   
4        1.0        1.0        3.0  -82.739825     14.388595  57.881783  1.0   

       q/pt  
0  0.033153  
1  0.021799  
2 -0.011223  
3  0.016987  
4  0.017277  

[5 rows x 27 columns]